name: Build and Publish to NuGet.org

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Release
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Replace GitHub token in nuget.config
        run: sed -i "s|%GITHUB_TOKEN%|${{ secrets.GITHUB_TOKEN }}|" NuGet.Config

      - name: Restore dependencies
        run: dotnet restore ./WiSave.Shared.Types/WiSave.Shared.Types.csproj

      - name: Build project
        run: dotnet build ./WiSave.Shared.Types/WiSave.Shared.Types.csproj --configuration $CONFIGURATION --no-restore

      - name: Set version number (timestamped)
        run: echo "VERSION=1.0.$(date +'%H%M%S')" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: |
          dotnet pack ./WiSave.Shared.Types/WiSave.Shared.Types.csproj \
            --configuration $CONFIGURATION \
            --output ./nupkgs \
            --include-symbols --include-source \
            /p:PackageVersion=$VERSION

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://nuget.pkg.github.com/JacobChwastek/index.json" \
            --api-key ${{ secrets.GH_PACKAGES_PAT }} \
            --skip-duplicate
    